language: python
python:
  - "3.7.0"
cache: pip
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install codecov
script:
  - cd test && coverage run -m tests test_search && cd ..

after_success:
  - bash <(curl -s https://codecov.io/bash)
