language: python
python:
  - "3.7.0"
cache: pip
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install codecov
script:
  - cd test && python3 tests.py && cd ..
  - cd test && python3 test_search.py
