language: python
python:
  - "3.7.0"
cache: pip
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install codecov
script:
  - cd tests.py && python3 test/tests.py
  - cd tests.py && python3 test/test_search.py
