language: python
python:
  - "3.7.0"
cache: pip
notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install codecov
  - pip install black
script:
  - black .
  - cd test && coverage run -m tests && coverage run -m -a test_search && coverage report -m && cd ..
after_success:
  - bash <(curl -s https://codecov.io/bash)
